version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
    - "jarikmarwede"
- package-ecosystem: npm
  directory: "/Back_End_Development_Certification/Voting_App"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
    - "jarikmarwede"
