services:
  database:
    image: "mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=nopass
      - MONGO_INITDB_DATABASE=voting-app
    volumes:
      - type: bind
        source: ./data
        target: /data/db
      - ./mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro
    expose:
      - 27017
  app:
    image: "node:22"
    working_dir: "/home/node/app"
    volumes:
      - "./:/home/node/app"
    ports:
      - "8080:8080"
    command: "npm start"
    environment:
      - DATABASE_PATH=mongodb://user:nopass@database/voting-app
    depends_on:
      - "database"
